-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglmbr12N3xOHuzD01
bpmsFzu2HiOiJjJ688LBJYRq0FygCgYIKoZIzj0DAQehRANCAASSKgMu4s0+QTwu
GuhErsOFhk7QJlgLiNUiRKYLHJc9RBXB3kr4qwAz4Gefmf/rPXW9DwXFQaHLQIy5
QOAeJ0qS
-----END PRIVATE KEY-----