project("./Pace & Plates.xcodeproj")
scheme("WorkingOut")
configuration("Debug")
devices([
  "iPhone 17 Pro Max",
  "iPhone 17 Pro",
  "iPad Pro 13-inch (M5)"
])
languages([
  "en-US"
])
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
skip_helper_version_check(true)
